# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/leds_const.xdc

# Block Designs: bd/timer_test2/timer_test2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer_test2 || ORIG_REF_NAME==timer_test2} -quiet] -quiet

# IP: bd/timer_test2/ip/timer_test2_processing_system7_0_0/timer_test2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer_test2_processing_system7_0_0 || ORIG_REF_NAME==timer_test2_processing_system7_0_0} -quiet] -quiet

# IP: bd/timer_test2/ip/timer_test2_axi_timer_0_0/timer_test2_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer_test2_axi_timer_0_0 || ORIG_REF_NAME==timer_test2_axi_timer_0_0} -quiet] -quiet

# IP: bd/timer_test2/ip/timer_test2_ps7_0_axi_periph_0/timer_test2_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer_test2_ps7_0_axi_periph_0 || ORIG_REF_NAME==timer_test2_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/timer_test2/ip/timer_test2_rst_ps7_0_102M_0/timer_test2_rst_ps7_0_102M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer_test2_rst_ps7_0_102M_0 || ORIG_REF_NAME==timer_test2_rst_ps7_0_102M_0} -quiet] -quiet

# IP: bd/timer_test2/ip/timer_test2_xbar_0/timer_test2_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer_test2_xbar_0 || ORIG_REF_NAME==timer_test2_xbar_0} -quiet] -quiet

# IP: bd/timer_test2/ip/timer_test2_axi_gpio_0_0/timer_test2_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer_test2_axi_gpio_0_0 || ORIG_REF_NAME==timer_test2_axi_gpio_0_0} -quiet] -quiet

# IP: bd/timer_test2/ip/timer_test2_auto_pc_0/timer_test2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timer_test2_auto_pc_0 || ORIG_REF_NAME==timer_test2_auto_pc_0} -quiet] -quiet

# XDC: bd/timer_test2/timer_test2_ooc.xdc
