# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/hypso/Documents/vivado/timer_test2/timer_test2.srcs/sources_1/bd/timer_test2/ip/timer_test2_rst_ps7_0_102M_0/timer_test2_rst_ps7_0_102M_0.xci
# IP: The module: 'timer_test2_rst_ps7_0_102M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hypso/Documents/vivado/timer_test2/timer_test2.srcs/sources_1/bd/timer_test2/ip/timer_test2_rst_ps7_0_102M_0/timer_test2_rst_ps7_0_102M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'timer_test2_rst_ps7_0_102M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/hypso/Documents/vivado/timer_test2/timer_test2.srcs/sources_1/bd/timer_test2/ip/timer_test2_rst_ps7_0_102M_0/timer_test2_rst_ps7_0_102M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'timer_test2_rst_ps7_0_102M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/hypso/Documents/vivado/timer_test2/timer_test2.srcs/sources_1/bd/timer_test2/ip/timer_test2_rst_ps7_0_102M_0/timer_test2_rst_ps7_0_102M_0.xci
# IP: The module: 'timer_test2_rst_ps7_0_102M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hypso/Documents/vivado/timer_test2/timer_test2.srcs/sources_1/bd/timer_test2/ip/timer_test2_rst_ps7_0_102M_0/timer_test2_rst_ps7_0_102M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'timer_test2_rst_ps7_0_102M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/hypso/Documents/vivado/timer_test2/timer_test2.srcs/sources_1/bd/timer_test2/ip/timer_test2_rst_ps7_0_102M_0/timer_test2_rst_ps7_0_102M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'timer_test2_rst_ps7_0_102M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
